default: &default
    debug: false
    local:
        port: 4029
    miner:
        port: 4028

development:
    <<: *default

test:
    <<: *default

staging:
    <<: *default

production: 
    <<: *default
    debug: false
