default: &default
    debug: false
    local:
        port: 4030
    miner:
        host: '127.0.0.1'
        port: 4028

development:
    <<: *default

test:
    <<: *default

staging:
    <<: *default

production: 
    <<: *default
    debug: false
